version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project-postgres
    restart: always
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

volumes:
  postgres_data:

networks:
  project-network:
    driver: bridge
